# Generated by Django 4.1.7 on 2023-03-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_is_etc'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_medicines',
        ),
        migrations.AddField(
            model_name='user',
            name='user_medicines',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='medicines.medicine'),
        ),
    ]
