# Generated by Django 4.1.7 on 2023-03-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=100, verbose_name='약국명')),
                ('address', models.CharField(max_length=140, verbose_name='주소')),
                ('callNumber1', models.CharField(max_length=20, verbose_name='연락처1')),
                ('callNumber2', models.CharField(max_length=20, verbose_name='연락처2')),
                ('coordinate_X', models.CharField(max_length=40)),
                ('coordinate_Y', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Pharmacies',
        ),
    ]
