# Generated by Django 4.1.7 on 2023-03-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_photo', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(verbose_name='작성일')),
                ('views', models.IntegerField(verbose_name='조회수')),
                ('title', models.CharField(max_length=140, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
