# Generated by Django 4.1.7 on 2023-03-13 03:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('review_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('title', models.CharField(max_length=140, verbose_name='제목')),
                ('content', models.TextField(null=True, verbose_name='내용')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('medicine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='medicines.medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
