# Generated by Django 4.1.7 on 2023-03-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
