# Generated by Django 4.1.7 on 2023-03-08 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('reviews', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='medicines.medicine'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
