# Generated by Django 4.1.7 on 2023-03-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('reviews', '0004_remove_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine'),
        ),
    ]
