# Generated by Django 4.1.7 on 2023-03-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='의약품명')),
                ('basis', models.CharField(max_length=140, verbose_name='주 성분')),
                ('effect', models.TextField(verbose_name='약효')),
                ('caution', models.TextField(verbose_name='주의사항')),
                ('cautionOtherMedicines', models.BooleanField(default=True, help_text='해당 DB를 아직 확인하지 않았기 때문에 default값 임시 저장한 상태.', verbose_name='다른 의약품과 함께 복용 가능지 여부')),
                ('is_etc', models.BooleanField(default=True)),
            ],
        ),
    ]
