# Generated by Django 4.1.7 on 2023-03-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='의약품명')),
                ('basis', models.TextField(verbose_name='주 성분')),
                ('effect', models.TextField(verbose_name='약효')),
                ('caution', models.TextField(verbose_name='주의사항')),
                ('cautionOtherMedicines', models.TextField(null=True, verbose_name='함께 복용 불가능한 의약품 목록')),
                ('etcChoices', models.CharField(blank=True, choices=[('ETC', '전문의약품'), ('OTC', '일반의약품')], max_length=3, verbose_name='전문의약품(ETC), 일반의약품(OTC)')),
            ],
        ),
    ]
