# Generated by Django 4.1.7 on 2023-03-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='is_etc',
            field=models.BooleanField(default=True, verbose_name='전문의약품(True), 일반의약품(False)'),
        ),
    ]
