# Generated by Django 4.1.7 on 2023-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mdPicturePath',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='이미지 경로'),
        ),
    ]
